"""Compile categorized + flagged items into an accountant-ready ledger."""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

from .models import LineItem
from . import schedule_c, config


def build(items: list[LineItem]) -> dict:
    income = [it for it in items if it.kind == "income"]
    expenses = [it for it in items if it.kind == "expense"]

    gross_receipts = round(sum(it.amount for it in income), 2)
    total_expenses = round(sum(it.amount for it in expenses), 2)
    total_deductible = round(sum(it.deductible_amount for it in expenses), 2)
    net_profit = round(gross_receipts - total_deductible, 2)

    by_line: dict[str, dict] = defaultdict(
        lambda: {"label": "", "count": 0, "claimed": 0.0, "deductible": 0.0})
    for it in expenses:
        code = it.raw.get("_line_code", "27a")
        b = by_line[code]
        b["label"] = schedule_c.line_label(code)
        b["count"] += 1
        b["claimed"] = round(b["claimed"] + it.amount, 2)
        b["deductible"] = round(b["deductible"] + it.deductible_amount, 2)

    flagged = [it for it in items if it.risk_level in ("medium", "high")]
    return {
        "tax_year": config.TAX_YEAR,
        "summary": {
            "documents": len({it.source for it in items}),
            "line_items": len(items),
            "gross_receipts": gross_receipts,
            "total_expenses_claimed": total_expenses,
            "total_deductible": total_deductible,
            "estimated_net_profit_schedule_c": net_profit,
            "flagged_items": len(flagged),
            "high_risk_items": sum(1 for it in items if it.risk_level == "high"),
        },
        "schedule_c_lines": {
            f"Line {code}": v for code, v in sorted(by_line.items())
        },
        "line_items": [it.to_dict() for it in items],
    }


def write_all(ledger: dict, items: list[LineItem], out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "ledger.json").write_text(
        json.dumps(ledger, indent=2), encoding="utf-8")
    _write_csv(items, out_dir / "ledger.csv")
    (out_dir / "audit_report.md").write_text(
        _markdown(ledger), encoding="utf-8")
    return {
        "ledger_json": str(out_dir / "ledger.json"),
        "ledger_csv": str(out_dir / "ledger.csv"),
        "audit_report_md": str(out_dir / "audit_report.md"),
    }


def _write_csv(items: list[LineItem], path: Path) -> None:
    cols = ["source", "profile", "date", "vendor", "description", "kind",
            "amount", "schedule_c_line", "deductible_pct", "deductible_amount",
            "confidence", "risk_level", "flags"]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for it in items:
            d = it.to_dict()
            d["flags"] = "; ".join(it.flags)
            w.writerow([d.get(c, "") for c in cols])


def _markdown(ledger: dict) -> str:
    s = ledger["summary"]
    lines = [
        f"# Schedule C Compliance Audit — Tax Year {ledger['tax_year']}",
        "",
        "## Summary",
        f"- Documents processed: **{s['documents']}**",
        f"- Line items: **{s['line_items']}**",
        f"- Gross receipts (1099-NEC + income): **${s['gross_receipts']:,.2f}**",
        f"- Total expenses claimed: **${s['total_expenses_claimed']:,.2f}**",
        f"- Total deductible (after limits): **${s['total_deductible']:,.2f}**",
        f"- Estimated net profit (Schedule C): **${s['estimated_net_profit_schedule_c']:,.2f}**",
        f"- Flagged items: **{s['flagged_items']}** ({s['high_risk_items']} high-risk)",
        "",
        "## Schedule C Expense Lines",
        "| Line | Category | # | Claimed | Deductible |",
        "|------|----------|---|---------|------------|",
    ]
    for line, v in ledger["schedule_c_lines"].items():
        lines.append(
            f"| {line} | {v['label']} | {v['count']} | "
            f"${v['claimed']:,.2f} | ${v['deductible']:,.2f} |")
    lines += ["", "## Flagged Items (review before filing)", ""]
    flagged = [it for it in ledger["line_items"]
               if it["risk_level"] in ("medium", "high")]
    if not flagged:
        lines.append("_No items flagged._")
    for it in sorted(flagged, key=lambda x: x["risk_level"], reverse=True):
        lines.append(
            f"- **[{it['risk_level'].upper()}]** {it.get('vendor') or '?'} "
            f"${it['amount']:,.2f} — {it.get('schedule_c_line') or 'uncategorized'} "
            f"({it['source']}): {'; '.join(it['flags'])}")
    lines += ["", "_Generated by the Independent Contractor Tax & Deduction "
              "Auditor. Not tax advice — for accountant review._"]
    return "\n".join(lines)
